name: Mfc Website
markdown: kramdown
url: https://certificate.mf-chan.com
permalink: /:categories/:slug

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"